import { IState } from '../models';

export const States: { [key: string]: IState } = {
  AC: { name: 'Acre', uf: 'AC' },
  AL: { name: 'Alagoas', uf: 'AL' },
  AP: { name: 'Amapá', uf: 'AP' },
  AM: { name: 'Amazonas', uf: 'AM' },
  BA: { name: 'Bahia', uf: 'BA' },
  CE: { name: 'Ceará', uf: 'CE' },
  DF: { name: 'Distrito Federal', uf: 'DF' },
  ES: { name: 'Espírito Santo', uf: 'ES' },
  GO: { name: 'Goiás', uf: 'GO' },
  MA: { name: 'Maranhão', uf: 'MA' },
  MT: { name: 'Mato Grosso', uf: 'MT' },
  MS: { name: 'Mato Grosso do Sul', uf: 'MS' },
  MG: { name: 'Minas Gerais', uf: 'MG' },
  PA: { name: 'Pará', uf: 'PA' },
  PB: { name: 'Paraíba', uf: 'PB' },
  PR: { name: 'Paraná', uf: 'PR' },
  PE: { name: 'Pernambuco', uf: 'PE' },
  PI: { name: 'Piauí', uf: 'PI' },
  RJ: { name: 'Rio de Janeiro', uf: 'RJ' },
  RN: { name: 'Rio Grande do Norte', uf: 'RN' },
  RS: { name: 'Rio Grande do Sul', uf: 'RS' },
  RO: { name: 'Rondônia', uf: 'RO' },
  RR: { name: 'Roraima', uf: 'RR' },
  SC: { name: 'Santa Catarina', uf: 'SC' },
  SP: { name: 'São Paulo', uf: 'SP' },
  SE: { name: 'Sergipe', uf: 'SE' },
  TO: { name: 'Tocantins', uf: 'TO' },
};
